version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test: 
   # working_directory: ~/
    docker:
      - image: cimg/python:3.10.5
   
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          
      - run:
          name: Run tests
          command: |
            make  install
            make lint
            echo "YOU ARE --> ${USER_NAME}"

      - run: 
          name: Running adhoc
          command: |
            echo "This is working fine."
            touch art-1
            echo "Temp: 35 deg" >art-t
#       - store_artifacts:
#             path: ~/art-1
#             destination: artifact-file
#       - store_artifacts:
#             path: ~/artifacts
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
